DROP TABLE IF EXISTS deposito CASCADE;

CREATE TABLE deposito (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          codigo VARCHAR(50) UNIQUE NOT NULL,
                          nombre VARCHAR(200) NOT NULL,
                          direccion VARCHAR(500),
                          ciudad VARCHAR(100),
                          responsable VARCHAR(100),
                          telefono VARCHAR(50),
                          observaciones VARCHAR(1000),
                          activo BOOLEAN DEFAULT TRUE,
                          es_principal BOOLEAN DEFAULT FALSE,
                          capacidad_maxima INTEGER,
                          fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
                          fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);